export { default as HomePage } from './HomePage'
export { default as AboutPage } from './AboutPage'
export { default as LoginPage } from './auth/LoginPage'
export { default as RegisterPage } from './auth/RegisterPage'
export { default as ForgotPasswordPage } from './auth/ForgotPasswordPage'
export { default as ProfilePage } from './profile/ProfilePage'
export { default as NotFoundPage } from './errors/NotFoundPage'
