export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    google: '/auth/google',
    facebook: '/auth/facebook',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  users: {
    byId: (id) => `/users/${id}`,
    profile: '/users/me/profile',
    jockeys: '/users/jockeys',
  },
  admin: {
    users: '/admin/users',
    userById: (id) => `/admin/users/${id}`,
    activeUsers: '/admin/users/active',
    deactivatedUsers: '/admin/users/deactivated',
    activateUser: (id) => `/admin/users/${id}/activate`,
    deactivateUser: (id) => `/admin/users/${id}/deactivate`,
    userRole: (id) => `/admin/users/${id}/role`,
    roleApplications: '/admin/role-applications',
    approveRoleApplication: (id) => `/admin/role-applications/${id}/approve`,
    rejectRoleApplication: (id) => `/admin/role-applications/${id}/reject`,
  },
  tournaments: {
    adminList: '/admin/tournaments',
    adminById: (id) => `/admin/tournaments/${id}`,
    adminBanners: '/admin/tournament-banners',
    adminStatus: (id) => `/admin/tournaments/${id}/status`,
    adminRaces: (id) => `/admin/tournaments/${id}/races`,
    adminRaceById: (id) => `/admin/races/${id}`,
    adminRaceRegistrations: (id) => `/admin/tournaments/${id}/race-registrations`,
    publicList: '/tournaments',
    publicById: (id) => `/tournaments/${id}`,
  },
  news: {
    list: '/news',
    all: '/news/all',
    byId: (id) => `/news/${id}`,
    adminList: '/admin/news',
    adminById: (id) => `/admin/news/${id}`,
  },
  horses: {
    ownerList: '/owner/horses',
    ownerById: (id) => `/owner/horses/${id}`,
    approved: '/horses/approved',
    adminList: '/admin/horses',
    adminApprove: (id) => `/admin/horses/${id}/approve`,
    adminReject: (id) => `/admin/horses/${id}/reject`,
    adminSuspend: (id) => `/admin/horses/${id}/suspend`,
  },
  jockeys: {
    available: '/jockeys/available',
    publicById: (id) => `/jockeys/${id}`,
    ownerInvitations: '/owner/jockey-invitations',
    ownerInvitationById: (id) => `/owner/jockey-invitations/${id}`,
    ownerCancelInvitation: (id) => `/owner/jockey-invitations/${id}/cancel`,
    ownerAccepted: '/owners/me/jockeys',
  },
  wallet: {
    me: '/wallets/me',
    transactions: '/wallets/me/transactions',
    depositOrders: '/wallets/me/deposit-orders',
    withdrawals: '/wallets/me/withdrawals',
    admin: '/admin/wallet',
    adminTransactions: '/admin/wallet/transactions',
  },
  roleApplications: {
    me: '/role-applications/me',
    owner: '/role-applications/owner',
    jockey: '/role-applications/jockey',
    spectator: '/role-applications/spectator',
    referee: '/role-applications/referee',
    adminList: '/admin/role-applications',
    adminApprove: (profileId) => `/admin/role-applications/${profileId}/approve`,
    adminReject: (profileId) => `/admin/role-applications/${profileId}/reject`,
  },
}
