export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    logout: '/auth/logout',
    me: '/auth/me',
    google: '/auth/google',
    facebook: '/auth/facebook',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
    updatePassword: '/auth/password',
  },
  users: {
    byId: (id) => `/users/${id}`,
    profile: '/users/me/profile',
    jockeys: '/users/jockeys',
  },
  admin: {
    users: '/admin/users',
    userById: (id) => `/admin/users/${id}`,
    activeUsers: '/admin/users/active',
    deactivatedUsers: '/admin/users/deactivated',
    activateUser: (id) => `/admin/users/${id}/activate`,
    deactivateUser: (id) => `/admin/users/${id}/deactivate`,
    userRole: (id) => `/admin/users/${id}/role`,
    roleApplications: '/admin/role-applications',
    approveRoleApplication: (id) => `/admin/role-applications/${id}/approve`,
    rejectRoleApplication: (id) => `/admin/role-applications/${id}/reject`,
  },
  locationSettings: {
    provinces: '/admin/provinces',
    provinceById: (id) => `/admin/provinces/${id}`,
    provinceActive: (id) => `/admin/provinces/${id}/active`,
    provinceVenues: (provinceId) => `/admin/provinces/${provinceId}/venues`,
    venueById: (id) => `/admin/venues/${id}`,
    venueActive: (id) => `/admin/venues/${id}/active`,
  },
  systemSettings: {
    admin: '/admin/system-settings',
    fees: '/admin/system-settings/fees',
    raceDistances: '/admin/system-settings/race-distances',
  },
  dashboard: {
    tournamentRegistrations: '/admin/dashboard/tournament-registrations',
  },
  spectator: {
    dashboard: '/spectator/dashboard',
  },
  tournaments: {
    adminList: '/admin/tournaments',
    adminById: (id) => `/admin/tournaments/${id}`,
    adminBanners: '/admin/tournament-banners',
    adminStatus: (id) => `/admin/tournaments/${id}/status`,
    adminSchedule: (id) => `/admin/tournaments/${id}/schedule`,
    adminRaces: (id) => `/admin/tournaments/${id}/races`,
    adminRaceById: (id) => `/admin/races/${id}`,
    adminRaceRegistrations: (id) => `/admin/tournaments/${id}/race-registrations`,
    adminVenues: (id) => `/admin/tournaments/${id}/venues`,
    publicList: '/tournaments',
    publicById: (id) => `/tournaments/${id}`,
    publicRaces: (id) => `/tournaments/${id}/races`,
    publicLeaderboard: (id) => `/tournaments/${id}/leaderboard`,
  },
  races: {
    assignReferee: (id) => `/admin/races/${id}/referee`,
    adminParticipants: (id) => `/admin/races/${id}/participants`,
    registrations: (id) => `/races/${id}/registrations`,
    results: (id) => `/races/${id}/results`,
  },
  betting: {
    publicMarket: (raceId) => `/races/${raceId}/bet-market`,
    bettableRaces: '/users/me/bettable-races',
    placeBet: (raceId) => `/races/${raceId}/bets`,
    myBets: '/users/me/bets',
    myBet: (id) => `/bets/${id}`,
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id) => `/notifications/${id}/read`,
    markAllRead: '/notifications/read-all',
  },
  refereeSalaryConfigs: {
    list: '/admin/referee-salary-configs',
    byId: (id) => `/admin/referee-salary-configs/${id}`,
  },
  referee: {
    races: '/referee/races',
    dashboard: '/referee/dashboard',
    checkedInCount: '/referee/dashboard/checked-in-count',
    pendingCheckInCount: '/referee/dashboard/pending-check-in-count',
    participants: (raceId) => `/referee/races/${raceId}/participants`,
    updateGate: (raceId, participantId) =>
      `/referee/races/${raceId}/participants/${participantId}/gate`,
    checkIn: (raceId, participantId) =>
      `/referee/races/${raceId}/participants/${participantId}/check-in`,
    startRace: (raceId) => `/referee/races/${raceId}/start`,
    finalizeResults: (raceId) => `/referee/races/${raceId}/results/finalize`,
  },
  raceRegistrations: {
    ownerList: '/owner/race-registrations',
    ownerWithdraw: (id) => `/owner/race-registrations/${id}/withdraw`,
    adminApprove: (id) => `/admin/race-registrations/${id}/approve`,
    adminReject: (id) => `/admin/race-registrations/${id}/reject`,
  },
  news: {
    list: '/news',
    all: '/news/all',
    byId: (id) => `/news/${id}`,
    adminList: '/admin/news',
    adminById: (id) => `/admin/news/${id}`,
  },
  horses: {
    ownerList: '/owner/horses',
    ownerById: (id) => `/owner/horses/${id}`,
    approved: '/horses/approved',
    adminList: '/admin/horses',
    adminApprove: (id) => `/admin/horses/${id}/approve`,
    adminReject: (id) => `/admin/horses/${id}/reject`,
    adminSuspend: (id) => `/admin/horses/${id}/suspend`,
  },
  jockeys: {
    available: '/jockeys/available',
    publicById: (id) => `/jockeys/${id}`,
    ownerInvitations: '/owner/jockey-invitations',
    ownerInvitationById: (id) => `/owner/jockey-invitations/${id}`,
    ownerCancelInvitation: (id) => `/owner/jockey-invitations/${id}/cancel`,
    ownerAccepted: '/owners/me/jockeys',
    jockeyInvitations: '/jockey/invitations',
    jockeyInvitationById: (id) => `/jockey/invitations/${id}`,
    jockeyAcceptInvitation: (id) => `/jockey/invitations/${id}/accept`,
    jockeyRejectInvitation: (id) => `/jockey/invitations/${id}/reject`,
  },
  wallet: {
    me: '/wallets/me',
    transactions: '/wallets/me/transactions',
    depositOrders: '/wallets/me/deposit-orders',
    depositOrderById: (id) => `/wallets/me/deposit-orders/${id}`,
    withdrawals: '/wallets/me/withdrawals',
    admin: '/admin/wallet',
    adminTransactions: '/admin/wallet/transactions',
    adminDepositOrders: '/admin/wallet/deposit-orders',
    adminDepositOrderById: (id) => `/admin/wallet/deposit-orders/${id}`,
    adminWithdrawals: '/admin/wallet/withdrawals',
  },
  roleApplications: {
    me: '/role-applications/me',
    owner: '/role-applications/owner',
    jockey: '/role-applications/jockey',
    spectator: '/role-applications/spectator',
    referee: '/role-applications/referee',
    kycOcr: '/role-applications/kyc/ocr',
    kycFaceMatch: (verificationId) =>
      `/role-applications/kyc/${verificationId}/face-match`,
    adminList: '/admin/role-applications',
    adminApprove: (profileId) => `/admin/role-applications/${profileId}/approve`,
    adminReject: (profileId) => `/admin/role-applications/${profileId}/reject`,
  },
}
