export { default as TournamentHero } from './TournamentHero'
export { default as OverviewTab } from './OverviewTab'
export { default as RacesTab } from './RacesTab'
export { default as ParticipantsTab } from './ParticipantsTab'
export { default as ScheduleTab } from './ScheduleTab'
export { default as ResultsTab } from './ResultsTab'
export { default as SettingsTab } from './SettingsTab'
export { default as TournamentPublicDetailContent } from './TournamentPublicDetailContent'
export { detailTabs } from './tabs'
